# application.yaml

server:
  # port: 8080
  # location on classpath (e.g. src/main/resources/WEB in maven)
  static.classpath:
    location: "/WEB"
    # this is optional, defaults to "/"
    context: "/web"
    welcome: "index.html"

grpc:
  port: 50051
  channels:                
    myserver:           
      host: localhost      
      port: 50051
   
# security settings - simple basic auth
# can work with oracle.demo.SecurityResource
security:
    providers:
    - abac:
    - http-basic-auth:
        realm: "helidon"
        users:
        - login: "john"
          password: "password"
          roles: ["user", "admin"]
        - login: "mary"
          password: "password"
          roles: ["user"]
        - login: "ken"
          password: "password"

# data source settings
javax:
    sql:
        DataSource:
            DemoDataSource:
                dataSourceClassName: org.h2.jdbcx.JdbcDataSource
                dataSource:
                    url: jdbc:h2:mem:greeting;INIT=RUNSCRIPT FROM 'classpath:createtable.ddl' 
                    user: sa
                    password: ""
